// Generates app/embed.ts: raw imports of the built frontend + schema, so bundles
// (snap / AppImage / dmg) carry the assets in the compile VFS — no disk layout needed.
// Run after `vite build` (wired into `just web-build` and CI).

const APP = new URL("../app/", import.meta.url).pathname;

async function listDist(dir: string, prefix = ""): Promise<string[]> {
  const out: string[] = [];
  try {
    for await (const e of Deno.readDir(`${APP}web/dist/${dir}`)) {
      const rel = `${dir}${prefix}${e.name}`;
      if (e.isDirectory) out.push(...await listDist(`${rel}/`));
      else out.push(rel);
    }
  } catch { /* no dist yet */ }
  return out;
}

const files = await listDist("");
if (!files.includes("index.html")) {
  console.error("gen-embed: app/web/dist/index.html missing — run the vite build first (`just web-build`)");
  Deno.exit(1);
}
const imports: string[] = [`import schemaSql from "../db/schema.sql" with { type: "text" };`];
const entries: string[] = [];
files.forEach((f, i) => {
  imports.push(`import a${i} from "./web/dist/${f}" with { type: "bytes" };`);
  entries.push(`  ${JSON.stringify(f)}: a${i},`);
});

const src = `// AUTO-GENERATED by scripts/gen-embed.ts — do not edit. Regenerate with \`just web-build\`.
${imports.join("\n")}

export const SCHEMA: string = schemaSql;
export const ASSETS: Record<string, Uint8Array> = {
${entries.join("\n")}
};
`;
await Deno.writeTextFile(`${APP}embed.ts`, src);
console.log(`embed.ts: ${files.length} asset(s) + schema embedded`);
