// Composes out-of-tree plugins into this checkout from the gitignored plugins.local.json:
//   { "plugins": ["../trame-cockpit"] }   (paths relative to the repo root, or absolute)
// A plugin checkout may hold mod.ts (backend), web/index.ts (frontend) and e2e/*.spec.ts.
// Writes the registries the app imports statically (no runtime loading: deno desktop + WebKitGTK).
// Without the file the registries are written empty, which is what the committed copies hold.
import { dirname, join, relative, resolve } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const OUT = {
  backend: join(ROOT, "app/plugins/local.gen.ts"),
  web: join(ROOT, "app/web/src/plugins/local.gen.ts"),
  css: join(ROOT, "app/web/src/plugins/local.gen.css"),
};
const exists = (p: string) => Deno.stat(p).then(() => true, () => false);

let paths: string[] = [];
try {
  paths = JSON.parse(await Deno.readTextFile(join(ROOT, "plugins.local.json"))).plugins ?? [];
} catch (e) {
  if (!(e instanceof Deno.errors.NotFound)) throw e;
}

const dirs = paths.map((p) => resolve(ROOT, p));
for (const d of dirs) {
  if (!await exists(d)) {
    console.error(`gen-plugins: ${d} (from plugins.local.json) does not exist`);
    Deno.exit(1);
  }
}

// relative import from a generated file, always ./-prefixed
const rel = (from: string, to: string) => {
  const r = relative(dirname(from), to);
  return r.startsWith(".") ? r : `./${r}`;
};
const HEADER = "// generated by scripts/gen-plugins.ts from plugins.local.json — do not edit\n";

async function registry(out: string, entry: string, type: string, typeFrom: string) {
  const found = [];
  for (const d of dirs) if (await exists(join(d, entry))) found.push(join(d, entry));
  return HEADER + `import type { ${type} } from "${typeFrom}";\n` +
    found.map((f, i) => `import p${i} from "${rel(out, f)}";\n`).join("") +
    `\nexport const LOCAL_PLUGINS: ${type}[] = [${found.map((_, i) => `p${i}`).join(", ")}];\n`;
}

const files: [string, string][] = [
  [OUT.backend, await registry(OUT.backend, "mod.ts", "Plugin", "./types.ts")],
  [OUT.web, await registry(OUT.web, "web/index.ts", "FrontendPlugin", "./index")],
  // tailwind only scans the app's own tree; point it at each plugin's web code
  [OUT.css, HEADER.replace("//", "/*").replace("\n", " */\n") +
    dirs.map((d) => `@source "${rel(OUT.css, join(d, "web"))}";\n`).join("")],
];
for (const [path, text] of files) await Deno.writeTextFile(path, text);

// a plugin resolves react / @playwright/test from the app's own node_modules (one copy of each)
for (const d of dirs) {
  const link = join(d, "node_modules");
  const isLink = await Deno.lstat(link).then((s) => s.isSymlink, () => null);
  if (isLink === false) continue; // the plugin's own node_modules
  if (isLink) await Deno.remove(link);
  await Deno.symlink(join(ROOT, "app/web/node_modules"), link);
}

// the committed copies stay empty: keep a composed checkout's copies out of commits
const flag = dirs.length ? "--skip-worktree" : "--no-skip-worktree";
await new Deno.Command("git", {
  args: ["update-index", flag, ...Object.values(OUT).map((p) => relative(ROOT, p))],
  cwd: ROOT,
}).output();

console.log(`gen-plugins: ${dirs.length ? dirs.join(", ") : "no local plugins"}`);
