// Generates hub/api/link-embed.ts: the public link viewer's built assets
// (app/web/dist-link, `npm run build:link`) inlined as base64, plus the entry
// js/css names parsed from link.html. Self-contained on purpose — deploy.sh
// ships hub/api/*.ts as-is, so the hub needs no dist directory or extra mounts.
// Run after the link build (wired into `deno task web:build`).

const APP = new URL("../app/", import.meta.url).pathname;
const HUB = new URL("../hub/api/", import.meta.url).pathname;
const DIST = `${APP}web/dist-link/`;

async function list(dir = ""): Promise<string[]> {
  const out: string[] = [];
  try {
    for await (const e of Deno.readDir(`${DIST}${dir}`)) {
      const rel = `${dir}${e.name}`;
      if (e.isDirectory) out.push(...await list(`${rel}/`));
      else out.push(rel);
    }
  } catch { /* no dist yet */ }
  return out;
}

const files = (await list()).filter((f) => f !== "link.html");
let html: string;
try {
  html = await Deno.readTextFile(`${DIST}link.html`);
} catch {
  console.error(
    "gen-link-embed: app/web/dist-link/link.html missing — run `npm run build:link` first (wired into `deno task web:build`)",
  );
  Deno.exit(1);
}
// the hub shell references the hashed entry files by name
const js = html.match(/src="\/l\/assets\/([^"]+\.js)"/)?.[1];
const css = [...html.matchAll(/href="\/l\/assets\/([^"]+\.css)"/g)].map((m) =>
  m[1]
);
if (!js) {
  console.error("gen-link-embed: no module entry found in dist-link/link.html");
  Deno.exit(1);
}

const TYPES: Record<string, string> = {
  js: "text/javascript; charset=utf-8",
  css: "text/css; charset=utf-8",
  svg: "image/svg+xml",
  png: "image/png",
  woff2: "font/woff2",
  map: "application/json",
};
const b64 = (bytes: Uint8Array): string => {
  let s = "";
  const CHUNK = 0x8000; // String.fromCharCode arg-count limit
  for (let i = 0; i < bytes.length; i += CHUNK) {
    s += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  return btoa(s);
};

const entries: string[] = [];
let total = 0;
for (const f of files) {
  const bytes = await Deno.readFile(`${DIST}${f}`);
  total += bytes.length;
  const type = TYPES[f.split(".").pop() ?? ""] ?? "application/octet-stream";
  entries.push(
    `  ${JSON.stringify(f)}: { type: ${JSON.stringify(type)}, b64:\n"${
      b64(bytes)
    }" },`,
  );
}

const src =
  `// AUTO-GENERATED by scripts/gen-link-embed.ts — do not edit. Regenerate with \`deno task web:build\` (app/).
export const LINK_ENTRY = { js: ${JSON.stringify(js)}, css: ${
    JSON.stringify(css)
  } };

const RAW: Record<string, { type: string; b64: string }> = {
${entries.join("\n")}
};

const decode = (b64: string): Uint8Array =>
  Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));

export const LINK_ASSETS: Record<string, { type: string; bytes: Uint8Array }> =
  Object.fromEntries(
    Object.entries(RAW).map((
      [k, v],
    ) => [k, { type: v.type, bytes: decode(v.b64) }]),
  );
`;
await Deno.writeTextFile(`${HUB}link-embed.ts`, src);
console.log(
  `link-embed.ts: ${files.length} asset(s), ${
    (total / 1024).toFixed(0)
  } KB embedded (entry: ${js})`,
);
